### ISSUE TITLE
Regarding Default Hostet

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/onestop_flutter#114]
### Description :
In the mess menu option, we have to select hostel every time, like I am from Brahmaputra and BPH is in options 3-4 so every time i have select to see menu, if I have save my hostel hai Brahmaputra my profile then, it should be by default BPH in menu.
### Posted By :
v.khurendra@iitg.ac.in - 234101055

**Comment by venkylm10** [comment]
I wanna work on this, can you guys assign this to me

**Comment by Hareesh-Nandigrama** [comment]
you have been assigned @venkylm10
