### ISSUE TITLE
Timetable Refactoring

### ISSUE THREAD

**Issue by Ashutosh-777** [swciitg/onestop_flutter#128]
### Summary

Data recieved from the backend is changed Change the code accordingly to new Json Response [ Both New and Old Json Respoonse are attached here for your Reference](https://drive.google.com/drive/folders/1H8c2-UqtW6Ga_csNXVwZ25ZaPg1TSfby?usp=sharing)
TimeTable is shown on both homepage and Timetable Page. Make sure to make changes wherever required

### Issue Assignment

No

**Comment by Priyammm05** [comment]
Please assign it to me @Ashutosh-777

**Comment by Ashutosh-777** [comment]
> Please assign it to me @Ashutosh-777

`JSON Response on the drive has been updated.`
Refer to the latest updated file.

**Comment by Priyammm05** [comment]
Yes I will check and start working on it.

**Comment by venkylm10** [comment]
in case no one is working on it currently, please assign it to me!

**Comment by Ashutosh-777** [comment]
> Yes I will check and start working on it.

@Priyammm05 still working ?

**Comment by venkylm10** [comment]
@Ashutosh-777 I would like to work on this if no one is working currently

**Comment by Ashutosh-777** [comment]
> @Ashutosh-777 I would like to work on this if no one is working currently

@venkylm10 you have been assigned
