### ISSUE TITLE
[BUG] - Inconsistent UI

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/onestop_flutter#208]
### Description

- Text in AppBar is not visible
- ElevatedButton design is not consistent with the app theme.
- Also fix the color of 'X' icon in Lost/Found, Buy/Sell and LAN pages

### Reproduction steps

```bash
1. Go to OneStop Home Screen
2. Click on Bell Icon (Top Right)
3. Click on Settings Icon (Top Right)
```

### Screenshots

![WhatsApp Image 2024-05-11 at 11 52 21_714c141d](https://github.com/swciitg/onestop_flutter/assets/95174582/75be6aca-e41a-4b82-959d-ecb1b08c5946)

### Platform

Android

**Comment by Hareesh-Nandigrama** [comment]
Also change the color of the x icon in contacts page, lnf page, bns page, lan page.

**Comment by Ashutosh-777** [comment]
Assigned to @ravishah6403
