### ISSUE TITLE
[BUG] - Retry button in Buy/Sell

### ISSUE THREAD

**Issue by hardikroongta8** [swciitg/onestop_flutter#210]
### Description

In case of an error during a network call, the screen displays an error message. It must display a retry button just like GC Scoreboard screens.
Use onestop_kit package: https://github.com/swciitg/onestop_kit
This package contains the widget for the error screen. Import this package in OneStop and use the widget in Lost/Found pages (for all three screens: For Sale, Requested Item, My Ads).

### Reproduction steps

```bash
1. Go to OneStop Home Screen
2. Turn off Internet
3. Click on Buy/Sell
4. See error
```

### Screenshots

![WhatsApp Image 2024-05-11 at 12 16 02_17995390](https://github.com/swciitg/onestop_flutter/assets/95174582/67b7bbc8-5e64-4e61-8f02-3a7312f3a415)

### Platform

Android

**Comment by Ashutosh-777** [comment]
@ramukumar7827 assigned to you
